included:
  - Sources

excluded:
  - .build

disabled_rules:
  - trailing_comma
  - opening_brace

opt_in_rules:
  - empty_count
  - closure_spacing
  - force_unwrapping
  - implicitly_unwrapped_optional

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 500
  error: 600

file_length:
  warning: 600
  error: 700

function_body_length:
  warning: 120
  error: 150
