import Foundation

let allLocalizationStrings: [String: [String: String]] = [
    "en": [
        "menu.toggle": "Effect ON",
        "menu.settings": "Settings...",
        "menu.about": "About RippleClick",
        "menu.quit": "Quit",
        "settings.effectEnabled": "Ripple effect",
        "settings.title": "RippleClick Settings",
        "settings.tab.ripple": "Ripple",
        "settings.tab.color": "Color",
        "settings.tab.sound": "Sound",
        "settings.tab.general": "General",
        "settings.color.appearance": "Match system appearance",
        "settings.color.light": "Light Mode",
        "settings.color.dark": "Dark Mode",
        "settings.size": "Ripple Size",
        "settings.speed": "Animation Speed",
        "settings.size.min": "Small",
        "settings.size.max": "Large",
        "settings.speed.min": "Fast",
        "settings.speed.max": "Slow",
        "settings.opacity": "Opacity",
        "settings.opacity.min": "Light",
        "settings.opacity.max": "Strong",
        "settings.launchAtLogin": "Launch at Login",
        "settings.clickType.left": "Left Click",
        "settings.clickType.right": "Right Click",
        "settings.clickType.double": "Double Click",
        "settings.clickType.rightEnabled": "Right-click ripple",
        "settings.clickType.doubleEnabled": "Double-click ripple",
        "settings.reset": "Reset to Defaults",
        "settings.reset.confirm.title": "Reset all settings to defaults?",
        "settings.reset.confirm.message":
            "Ripple, color, sound and general settings all return to their initial values. "
            + "This can't be undone.",
        "common.cancel": "Cancel",
        "color.cyan": "Cyan",
        "color.blue": "Blue",
        "color.navy": "Navy",
        "color.purple": "Purple",
        "color.pink": "Pink",
        "color.red": "Red",
        "color.orange": "Orange",
        "color.yellow": "Yellow",
        "color.lime": "Lime",
        "color.green": "Green",
        "color.teal": "Teal",
        "color.white": "White",
        "settings.sound.enabled": "Click sound",
        "settings.sound.type": "Sound type",
        "settings.sound.volume": "Volume",
        "settings.sound.volume.min": "Quiet",
        "settings.sound.volume.max": "Loud",
        "settings.sound.preview": "Preview sound",
        "sound.type.waterDrop": "Water Drop",
        "sound.type.pop": "Pop",
        "sound.type.sonar": "Sonar",
        "sound.type.bubble": "Bubble",
        "sound.type.softClick": "Soft Click",
    ],
    "ja": [
        "menu.toggle": "エフェクト ON",
        "menu.settings": "設定...",
        "menu.about": "RippleClick について",
        "menu.quit": "終了",
        "settings.effectEnabled": "波紋エフェクト",
        "settings.title": "RippleClick 設定",
        "settings.tab.ripple": "波紋",
        "settings.tab.color": "色",
        "settings.tab.sound": "サウンド",
        "settings.tab.general": "一般",
        "settings.color.appearance": "システム外観に合わせて色を変更",
        "settings.color.light": "ライトモード",
        "settings.color.dark": "ダークモード",
        "settings.size": "波紋の最大サイズ",
        "settings.speed": "アニメーション速度",
        "settings.size.min": "小",
        "settings.size.max": "大",
        "settings.speed.min": "速い",
        "settings.speed.max": "遅い",
        "settings.opacity": "不透明度",
        "settings.opacity.min": "薄い",
        "settings.opacity.max": "濃い",
        "settings.launchAtLogin": "ログイン時に自動起動",
        "settings.clickType.left": "左クリック",
        "settings.clickType.right": "右クリック",
        "settings.clickType.double": "ダブルクリック",
        "settings.clickType.rightEnabled": "右クリック波紋",
        "settings.clickType.doubleEnabled": "ダブルクリック波紋",
        "settings.reset": "デフォルトに戻す",
        "settings.reset.confirm.title": "設定をデフォルトに戻しますか？",
        "settings.reset.confirm.message":
            "波紋・色・サウンド・一般のすべての設定が初期値に戻ります。この操作は取り消せません。",
        "common.cancel": "キャンセル",
        "color.cyan": "シアン",
        "color.blue": "ブルー",
        "color.navy": "ネイビー",
        "color.purple": "パープル",
        "color.pink": "ピンク",
        "color.red": "レッド",
        "color.orange": "オレンジ",
        "color.yellow": "イエロー",
        "color.lime": "ライム",
        "color.green": "グリーン",
        "color.teal": "ティール",
        "color.white": "ホワイト",
        "settings.sound.enabled": "クリック音",
        "settings.sound.type": "効果音の種類",
        "settings.sound.volume": "音量",
        "settings.sound.volume.min": "小",
        "settings.sound.volume.max": "大",
        "settings.sound.preview": "サウンドを再生",
        "sound.type.waterDrop": "水滴",
        "sound.type.pop": "ポップ",
        "sound.type.sonar": "ソナー",
        "sound.type.bubble": "バブル",
        "sound.type.softClick": "ソフトクリック",
    ],
    "zh-Hans": [
        "menu.toggle": "效果 ON",
        "menu.settings": "设置...",
        "menu.about": "关于 RippleClick",
        "menu.quit": "退出",
        "settings.effectEnabled": "波纹效果",
        "settings.title": "RippleClick 设置",
        "settings.tab.ripple": "波纹",
        "settings.tab.color": "颜色",
        "settings.tab.sound": "音效",
        "settings.tab.general": "通用",
        "settings.color.appearance": "根据系统外观更改颜色",
        "settings.color.light": "浅色模式",
        "settings.color.dark": "深色模式",
        "settings.size": "波纹最大尺寸",
        "settings.speed": "动画速度",
        "settings.size.min": "小",
        "settings.size.max": "大",
        "settings.speed.min": "快",
        "settings.speed.max": "慢",
        "settings.opacity": "不透明度",
        "settings.opacity.min": "淡",
        "settings.opacity.max": "浓",
        "settings.launchAtLogin": "登录时自动启动",
        "settings.clickType.left": "左键点击",
        "settings.clickType.right": "右键点击",
        "settings.clickType.double": "双击",
        "settings.clickType.rightEnabled": "右键波纹",
        "settings.clickType.doubleEnabled": "双击波纹",
        "settings.reset": "恢复默认设置",
        "settings.reset.confirm.title": "要将所有设置恢复为默认值吗？",
        "settings.reset.confirm.message": "波纹、颜色、声音和通用设置都将恢复为初始值。此操作无法撤销。",
        "common.cancel": "取消",
        "color.cyan": "青色",
        "color.blue": "蓝色",
        "color.navy": "海军蓝",
        "color.purple": "紫色",
        "color.pink": "粉色",
        "color.red": "红色",
        "color.orange": "橙色",
        "color.yellow": "黄色",
        "color.lime": "黄绿色",
        "color.green": "绿色",
        "color.teal": "蓝绿色",
        "color.white": "白色",
        "settings.sound.enabled": "点击音效",
        "settings.sound.type": "音效类型",
        "settings.sound.volume": "音量",
        "settings.sound.volume.min": "小",
        "settings.sound.volume.max": "大",
        "settings.sound.preview": "预览音效",
        "sound.type.waterDrop": "水滴",
        "sound.type.pop": "气泡",
        "sound.type.sonar": "声呐",
        "sound.type.bubble": "冒泡",
        "sound.type.softClick": "轻击",
    ],
    "ko": [
        "menu.toggle": "이펙트 ON",
        "menu.settings": "설정...",
        "menu.about": "RippleClick 정보",
        "menu.quit": "종료",
        "settings.effectEnabled": "물결 효과",
        "settings.title": "RippleClick 설정",
        "settings.tab.ripple": "파문",
        "settings.tab.color": "색상",
        "settings.tab.sound": "사운드",
        "settings.tab.general": "일반",
        "settings.color.appearance": "시스템 외관에 맞춰 색상 변경",
        "settings.color.light": "라이트 모드",
        "settings.color.dark": "다크 모드",
        "settings.size": "파문 최대 크기",
        "settings.speed": "애니메이션 속도",
        "settings.size.min": "작게",
        "settings.size.max": "크게",
        "settings.speed.min": "빠르게",
        "settings.speed.max": "느리게",
        "settings.opacity": "불투명도",
        "settings.opacity.min": "연하게",
        "settings.opacity.max": "진하게",
        "settings.launchAtLogin": "로그인 시 자동 실행",
        "settings.clickType.left": "좌클릭",
        "settings.clickType.right": "우클릭",
        "settings.clickType.double": "더블클릭",
        "settings.clickType.rightEnabled": "우클릭 파문",
        "settings.clickType.doubleEnabled": "더블클릭 파문",
        "settings.reset": "기본값으로 복원",
        "settings.reset.confirm.title": "모든 설정을 기본값으로 되돌릴까요?",
        "settings.reset.confirm.message":
            "물결, 색상, 사운드, 일반 설정이 모두 초기값으로 돌아갑니다. 이 작업은 되돌릴 수 없습니다.",
        "common.cancel": "취소",
        "color.cyan": "시안",
        "color.blue": "블루",
        "color.navy": "네이비",
        "color.purple": "퍼플",
        "color.pink": "핑크",
        "color.red": "레드",
        "color.orange": "오렌지",
        "color.yellow": "옐로",
        "color.lime": "라임",
        "color.green": "그린",
        "color.teal": "틸",
        "color.white": "화이트",
        "settings.sound.enabled": "클릭 사운드",
        "settings.sound.type": "효과음 종류",
        "settings.sound.volume": "볼륨",
        "settings.sound.volume.min": "작게",
        "settings.sound.volume.max": "크게",
        "settings.sound.preview": "사운드 미리 듣기",
        "sound.type.waterDrop": "물방울",
        "sound.type.pop": "팝",
        "sound.type.sonar": "소나",
        "sound.type.bubble": "버블",
        "sound.type.softClick": "소프트 클릭",
    ],
]

private let currentLanguage: String = {
    let supported = Array(allLocalizationStrings.keys)
    let preferred = Bundle.preferredLocalizations(from: supported)
    return preferred.first ?? "en"
}()

func localized(_ key: String) -> String {
    allLocalizationStrings[currentLanguage]?[key] ?? allLocalizationStrings["en"]?[key] ?? key
}
